// login Actions
export const GET_LOGIN_TOKEN = "GET_LOGIN_TOKEN"
export const GET_LOGIN_DATA = "GET_LOGIN_DATA"
export const GET_AUTH_ID = "GET_AUTH_ID"

//blog catagory actions
export const GET_BLOG_CATAGORY_DATA = "GET_BLOG_CATAGORY_DATA"
export const EDIT_BLOG_CATAGORY_DATA = "EDIT_BLOG_CATAGORY_DATA"

//blog management action
export const GET_BLOG_MANAGEMENT_DATA = "GET_BLOG_MANAGEMENT_DATA"
export const GET_BLOG_MANAGEMENT_DATA_WITH_ID = "GET_BLOG_MANAGEMENT_DATA_WITH_ID"
export const EDIT_BLOG_MANAGEMENT_DATA = "EDIT_BLOG_MANAGEMENT_DATA"


//FirstPage Action
export const GET_FIRST_PAGE_ALL_BLOG_DATA = "GET_FIRST_PAGE_ALL_BLOG_DATA"
export const GET_FIRST_PAGE_ALL_BLOG_DATA_NEXT_PAGE = "GET_FIRST_PAGE_ALL_BLOG_DATA_NEXT_PAGE"
export const GET_BLOG_DATA_PERTICULAR_ID = "GET_BLOG_DATA_PERTICULAR_ID"
export const GET_MAIN_USER_BLOG_DATA_PERTICULAR_ID = "GET_MAIN_USER_BLOG_DATA_PERTICULAR_ID"
export const GET_USER_BLOG_DATA = "GET_USER_BLOG_DATA"
export const GET_ALL_USER_BLOG_ID = "GET_ALL_USER_BLOG_ID"
export const SET_VALUE_OF_MENU_FLAG = "SET_VALUE_OF_MENU_FLAG"
