// login Actions
export const GET_LOGIN_TOKEN = "GET_LOGIN_TOKEN"
export const GET_LOGIN_DATA = "GET_LOGIN_DATA"
export const GET_AUTH_ID = "GET_AUTH_ID"

//get user list Action
export const GET_AVAILABLE_USER_LIST = "GET_AVAILABLE_USER_LIST"
export const GET_BLOG_DATA_PERTICULAR_ID = "GET_BLOG_DATA_PERTICULAR_ID"
export const UPDATE_DATA_BLOG = "UPDATE_DATA_BLOG"
export const GET_ONE_BLOG_ID = "GET_ONE_BLOG_ID"

//chat data with user array
export const MSG_DATA_FIRST_PAGE = "MSG_DATA_FIRST_PAGE"
export const MSG_DATA_WITH_USER = "MSG_DATA_WITH_USER"

//FirstPage Action
export const GET_TOTAL_COUNT_OF_BLOG = "GET_TOTAL_COUNT_OF_BLOG"
export const GET_FIRST_PAGE_ALL_BLOG_DATA = "GET_FIRST_PAGE_ALL_BLOG_DATA"
export const GET_FIRST_PAGE_ALL_BLOG_DATA_NEXT_PAGE = "GET_FIRST_PAGE_ALL_BLOG_DATA_NEXT_PAGE"
export const GET_MAIN_USER_BLOG_DATA_PERTICULAR_ID = "GET_MAIN_USER_BLOG_DATA_PERTICULAR_ID"
export const GET_USER_BLOG_DATA = "GET_USER_BLOG_DATA"
export const GET_ALL_USER_BLOG_ID = "GET_ALL_USER_BLOG_ID"
export const SET_VALUE_OF_MENU_FLAG = "SET_VALUE_OF_MENU_FLAG"
